apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/polyfea/manifests//gitops/fluxcd

configMapGenerator:
- name: polyfea-shell-cfg
  namespace: polyfea
  options:
    disableNameSuffixHash: true
  literals:
  - APP_TITLE=Nemocnica WAC
  - SERVICE_TYPE=NodePort
  - NODE_PORT=30331
  - CSP_HEADER=default-src 'self'; font-src 'self'; script-src 'strict-dynamic' 'nonce-{NONCE_VALUE}'; worker-src 'self'; manifest-src 'self'; style-src 'self' 'strict-dynamic' 'nonce-{NONCE_VALUE}'; style-src-attr 'self' 'unsafe-inline'; img-src *; connect-src 'self' localhost:30331 localhost:30081;